version: 0.1.0
identifier:
  id: ~
server_location: redis://127.0.0.1:6379
game_map:
  ? id: game1
  : puzzles:
      ? id: 1000
      : current_state:
          id: 1001
        available_state:
          id: 1001
        starting_state:
          id: 1002
        starting_event:
          id: 1005
        score_map:
          ? id: 1003
          : 400
          ? id: 1001
          : 0
minerva_controllers:
- game_id:
    id: game1
  address: ~